### ISSUE TITLE
Name of the users

### ISSUE THREAD

**Issue by nachopavon** [ColdTrick/elasticsearch#5]
Hi, I've been trying your plugin, but can only find in the search advanced some of my user's names, not all of them... tried reindexing, deleting the index and creating a new one... but still only finds some of them... If i use the username, instead of the name, it works fine.
The same happens for me in the groups and subgroups.
¿Anything i have to change in order to get all the names in elasticsearch? ¿or any advise to figure it out?
Thanks in advence.

**Comment by jdalsem** [comment]
Is the data synchronized to elasticsearch?
Is elasticsearch configured to handle the search requests?

If you are using search_advanced, is that plugin _not_ controlling the search results?

**Comment by nachopavon** [comment]
Yes, data is synchronized and elasticsearch is handling the search requests.
But if i search for member "Nacho Pavon" (without the quotes) only finds content related to that member.
If i search for member "nachopavon" (without the quotes), everything is fine and finds the member in the users section of advanced search.
So it looks like a problem with the name field.
Using the stock search makes no difference.
Thanks again for responding.

**Comment by jdalsem** [comment]
Do you have the same issue with other members? Can you find other content, like groups or blogs based on their title/name?

**Comment by nachopavon** [comment]
I have tried with blogs, events and pages and is working fine finding by title, but for groups it is finding in other fields, but not allways in the name of the group. For example, i have a group called BestGroup, and it finds all the subgroups for BestGroup, but not BestGroup itself. If you care I'm using elgg 2.2, elsaticsearch 2.4.4-1.
Regards

**Comment by jdalsem** [comment]
Closing this issue as there is currently no information on how to reproduce this problem and i am currently not experiencing the issue
