### ISSUE TITLE
ENHANCE: search within documents

### ISSUE THREAD

**Issue by mattip** [ColdTrick/elasticsearch#6]
Thanks for the plugin. I am new to elasticsearch, any help you can point me to would be kind. I am trying to search within PDF files.

I run [fscrawler](https://github.com/dadoonet/fscrawler) to add document content to elasticsearch, and can see from Kibana that the documents are indeed scanned.

``fscrawler`` puts the text into the ``content`` field of a ``doc`` ``_type`` in elasticsearch. How can I turn that to something elgg can access?

**Comment by jeabakker** [comment]
register a plugin hook onto this hook https://github.com/ColdTrick/elasticsearch/blob/master/classes/ColdTrick/ElasticSearch/SearchHooks.php#L324 and add 'content' as a field, that should probably do it

**Comment by jdalsem** [comment]
this plugin will no longer receive any new features... fancy stuff will maybe make it into the alternative at coldtrick/opensearch
